<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Back Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are fragments that are used dynamically in
    | Blender. Interface strings are generally hardcoded throughout the UI,
    | but sometimes a message is generated by some utility code, not giving
    | us control over the exact translations.
    |
    */

    'models' => [
        'articles' => 'Article',
        'news' => 'Article',
        'people' => 'Member',
        'redirects' => 'Redirect',
        'tags' => 'Tag',
        'recipients' => 'Recipient',
    ],

    'tags' => [
        'newsCategory' => 'News category',
        'newsTag' => 'News tag',
    ],

];
